export const PALETTE = {
  COLOR_PALETTE_BLUE_DARKER_14: '#0F94D1',
  COLOR_PALETTE_BLUE_BASE: '#2CBDFB',
  COLOR_PALETTE_BLUE_LIGHTER_37: '#E6F8FF',

  COLOR_PALETTE_PURPLE_DARKER_10: '#7714FF',
  COLOR_PALETTE_PURPLE_BASE: '#9447FF',
  COLOR_PALETTE_PURPLE_LIGHTER_30: '#EDDFFF',

  COLOR_PALETTE_RED_DARKER_14: '#B33B20',
  COLOR_PALETTE_RED_BASE: '#EF4F2B',
  COLOR_PALETTE_RED_LIGHTER_38: '#F9E7E2',

  COLOR_PALETTE_GRAY_DARKER_40: '#1A1A1A',
  COLOR_PALETTE_GRAY_DARKER_20: '#4D4D4D',
  COLOR_PALETTE_GRAY_BASE: '#808080',
  COLOR_PALETTE_GRAY_LIGHTER_20: '#B2B2B2',
  COLOR_PALETTE_GRAY_LIGHTER_30: '#C6C6C6',
  COLOR_PALETTE_GRAY_LIGHTER_40: '#E8E8E8',
  COLOR_PALETTE_GRAY_LIGHTER_48: '#FAFAFA',
};
