import { PALETTE } from './palette';

export const TEXT = {
  COLOR_TEXT_01: '#181740',
  COLOR_TEXT_02: '#5E5D84',
  COLOR_TEXT_03: '#969BB8',
  COLOR_TEXT_INVERSE: '#FFFFFF',
  COLOR_TEXT_LINK: '#0D7EB2',
  COLOR_TEXT_ERROR: PALETTE.COLOR_PALETTE_RED_BASE,
};
