export const LINE_HEIGHT = {
  TYPO_LINE_HEIGHT_H1: '64px',
  TYPO_LINE_HEIGHT_H2: '48px',
  TYPO_LINE_HEIGHT_H3: '32px',
  TYPO_LINE_HEIGHT_H4: '24px',
  TYPO_LINE_HEIGHT_BODY_L: '32px',
  TYPO_LINE_HEIGHT_BODY_M: '28px',
  TYPO_LINE_HEIGHT_BODY_S: '24px',
  TYPO_LINE_HEIGHT_LINK: '28px',
  TYPO_LINE_HEIGHT_QUOTE: '40px',
};
